### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lodenrogue** [phstc/javapokertexasholdem#3]
Hello, I was wondering what license this code is under?

**Comment by phstc** [comment]
Hey @lodenrogue 

hm I can add license file, does `LGPLv3` work for you?

**Comment by lodenrogue** [comment]
Yes, thank you

**Comment by phstc** [comment]
@lodenrogue done [LICENSE](https://github.com/phstc/javapokertexasholdem/blob/master/LICENSE).
