### ISSUE TITLE
Problem in evaluation

### ISSUE THREAD

**Issue by StefanOltmann** [phstc/javapokertexasholdem#4]
If you add a "Hearts King" card to your RankingTest.testCheckRoyalFlush() you will see that a isSameSuit() check of all cards is incorrect if you have more than your 5 cards. If you have to select 5 out of 7 this does not work. The same is true for the Straight Flush.

**Comment by phstc** [comment]
Thanks @StefanOltmann. This project isn't current maintained, but if you are able to submit a PR, I would be glad to review it.
